[env]
DRIVER_IMAGE = "partmgr"

[tasks.build-driver]
description = ""
dependencies = ["pre-build", "build", "copy-toml"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.pre-build]
script_runner = "cmd"
script = [
    "if not exist \"..\\..\\target\\DRIVERS\\%DRIVER_IMAGE%\" mkdir \"..\\..\\target\\DRIVERS\\%DRIVER_IMAGE%\"",
]

[tasks.copy-toml]
script_runner = "cmd"
script = [
    "copy /Y \"src\\%DRIVER_IMAGE%.toml\" \"..\\..\\target\\DRIVERS\\%DRIVER_IMAGE%\\%DRIVER_IMAGE%.toml\"",
]
