cargo-features = ["profile-rustflags"]

[package]
name = "kernel_types"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]


[dependencies]
kernel_macros = { path = "../kernel_macros" }

strum = { version = "0.24", default-features = false, features = ["derive"] }
acpi = "5.0.0"
spin = "0.10.0"
bincode = { version = "2.0.1", default-features = false, features = [
    "alloc",
    "derive",
] }
crossbeam-queue = { version = "0.3", default-features = false, features = [
    "alloc",
] }
array-init = "2.0.0"
prost = { version = "0.14.3", default-features = false, features = ["derive"] }

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = { version = "0.15.2", default-features = false, features = [
    "instructions",
] }

[features]
default = []
macros = []
hosted-tests = []
[profile.dev]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
debug = true

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
debug = true
