pub(crate) mod controller;
pub(crate) mod discovery;
pub(crate) mod entry;
pub(crate) mod gicv2m;
pub(crate) mod gicv3;
pub(crate) mod init;
pub(crate) mod its;
pub(crate) mod msi;
pub(crate) mod platform;
