pub const KERNEL_SPACE_BASE: u64 =
    kernel_abi::layout::aarch64::BOOT_VIRTUAL_LAYOUT.kernel_image_base;
pub const MMIO_BASE: u64 = 0xFFFF_9000_0000_0000;
pub const MANAGED_KERNEL_RANGE_START: u64 = MMIO_BASE;
pub const HEAP_RANGE_START: u64 = 0xFFFF_C000_0000_0000;
pub const HEAP_RANGE_END: u64 = 0xFFFF_FFFF_8000_0000;
pub const MANAGED_KERNEL_RANGE_END: u64 = HEAP_RANGE_START;
pub const LOW_PHYSICAL_RESERVE_BYTES: u64 = 2 * 1024 * 1024;

const _: () = assert!(KERNEL_SPACE_BASE < MANAGED_KERNEL_RANGE_START);
const _: () = assert!(MANAGED_KERNEL_RANGE_START < MANAGED_KERNEL_RANGE_END);
const _: () = assert!(MANAGED_KERNEL_RANGE_END == HEAP_RANGE_START);
const _: () = assert!(HEAP_RANGE_START < HEAP_RANGE_END);
