[unstable]
bindeps = true
json-target-spec = true

[target.x86_64-unknown-none]
rustflags = ["-C", "code-model=large"]

[profile.dev.package.kernel]
rustflags = ["-C", "panic=abort"]

[profile.release.package.kernel]
rustflags = ["-C", "panic=abort"]
