use core::arch::naked_asm;

use crate::scheduling::scheduler::{ipi_eoi_only, ipi_handler_c, kernel_task_end, yield_handler_c};
use crate::scheduling::task::{IDLE_MAGIC_LOWER, IDLE_UUID_UPPER};

#[unsafe(naked)]
#[no_mangle]
pub extern "C" fn ipi_entry() {
    naked_asm!(
        "/* {upper} {lower} {eoi_only} */",
        "cli",
        "push rax",
        "mov  rax, {upper}",
        "cmp  r10, rax",
        "jne  9f",
        "mov  rax, {lower}",
        "cmp  r11, rax",
        "jne  9f",
        "pop  rax",
        "push r15",
        "push r14",
        "push r13",
        "push r12",
        "push r11",
        "push r10",
        "push r9",
        "push r8",
        "push rdi",
        "push rsi",
        "push rbp",
        "push rbx",
        "push rdx",
        "push rcx",
        "push rax",
        "mov  rcx, rsp",
        "mov  rbx, rsp",
        "cld",
        "and  rsp, -16",
        "sub  rsp, 32",
        "call {handler}",
        "mov  rsp, rbx",
        "pop  rax",
        "pop  rcx",
        "pop  rdx",
        "pop  rbx",
        "pop  rbp",
        "pop  rsi",
        "pop  rdi",
        "pop  r8",
        "pop  r9",
        "pop  r10",
        "pop  r11",
        "pop  r12",
        "pop  r13",
        "pop  r14",
        "pop  r15",
        "iretq",
        "9:",
        "pop  rax",
        "push r15",
        "push r14",
        "push r13",
        "push r12",
        "push r11",
        "push r10",
        "push r9",
        "push r8",
        "push rdi",
        "push rsi",
        "push rbp",
        "push rbx",
        "push rdx",
        "push rcx",
        "push rax",
        "cld",
        "mov  rbx, rsp",
        "and  rsp, -16",
        "sub  rsp, 32",
        "call {eoi_only}",
        "mov  rsp, rbx",
        "pop  rax",
        "pop  rcx",
        "pop  rdx",
        "pop  rbx",
        "pop  rbp",
        "pop  rsi",
        "pop  rdi",
        "pop  r8",
        "pop  r9",
        "pop  r10",
        "pop  r11",
        "pop  r12",
        "pop  r13",
        "pop  r14",
        "pop  r15",
        "iretq",
        upper = const IDLE_UUID_UPPER,
        lower = const IDLE_MAGIC_LOWER,
        handler = sym ipi_handler_c,
        eoi_only = sym ipi_eoi_only,
    );
}

#[unsafe(naked)]
pub extern "C" fn yield_interrupt_entry() {
    naked_asm!(
        "cli",
        "push r15",
        "push r14",
        "push r13",
        "push r12",
        "push r11",
        "push r10",
        "push r9",
        "push r8",
        "push rdi",
        "push rsi",
        "push rbp",
        "push rbx",
        "push rdx",
        "push rcx",
        "push rax",
        "mov  rcx, rsp",
        "mov  rbx, rsp",
        "cld",
        "and  rsp, -16",
        "sub  rsp, 32",
        "call {handler}",
        "mov  rsp, rbx",
        "pop  rax",
        "pop  rcx",
        "pop  rdx",
        "pop  rbx",
        "pop  rbp",
        "pop  rsi",
        "pop  rdi",
        "pop  r8",
        "pop  r9",
        "pop  r10",
        "pop  r11",
        "pop  r12",
        "pop  r13",
        "pop  r14",
        "pop  r15",
        "iretq",
        handler = sym yield_handler_c,
    );
}

#[unsafe(naked)]
pub extern "C" fn task_return_trampoline() -> ! {
    naked_asm!(
        "cld",
        "sub rsp, 8",
        "mov qword ptr [rsp], 0",
        "jmp {task_end}",
        task_end = sym kernel_task_end,
    );
}

#[unsafe(naked)]
pub(crate) extern "C" fn idle_task(_ctx: usize) {
    naked_asm!("3:", "hlt", "jmp 3b",);
}
