cargo-features = ["profile-rustflags"]

[workspace]
members = [ "driver_test",
    "elf_test",
]
resolver = "2"

[profile.dev]
panic = "abort"
codegen-units = 1
lto = true
strip = true
opt-level = "z"


[profile.release]
panic = "abort"
codegen-units = 1
lto = true
strip = true
opt-level = "z"