[build]
target = "x86_64-pc-windows-msvc"

[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "panic=abort",

    "-Z", "pre-link-arg=/NODEFAULTLIB",       
    "-Z", "pre-link-arg=/NODEFAULTLIB:libcmt", 
    "-Z", "pre-link-arg=/NODEFAULTLIB:oldnames",

    "-Z", "pre-link-arg=/SUBSYSTEM:NATIVE",
    "-Z", "pre-link-arg=/DYNAMICBASE",
    "-Z", "pre-link-arg=/FIXED:NO",
    "-C", "link-arg=/ENTRY:mainCRTStartup",
]

[unstable]
build-std          = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]